# Use OpenJDK 17
FROM eclipse-temurin:17-jdk-alpine

# Set working directory inside the container
WORKDIR /app

# Copy the JAR built by Maven
COPY target/todo-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your Spring Boot app runs on 
EXPOSE 8080

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]
